FROM arm32v7/python:3.8.3-slim-buster

WORKDIR /python-docker

COPY requirements.txt requirements.txt
RUN apt-get update \
    && apt-get -y install libpq-dev gcc \
    && pip install -r requirements.txt

COPY . .

ENV FLASK_ENV=production
ENV FLASK_APP=viewer

CMD ["python3", "-m" , "flask", "run", "--host=0.0.0.0"]

